// functions/api/parse-plan.js
// Cloudflare Pages Function. Runs server-side — the Anthropic key lives only
// here as an encrypted env var, never in the browser bundle.
//
// Set the key once with:
//   wrangler pages secret put ANTHROPIC_API_KEY --project-name summit
// or via the Cloudflare dashboard: project -> Settings -> Environment variables.

const MODEL = "claude-sonnet-4-6";
const ANTHROPIC_VERSION = "2023-06-01";

const SYSTEM_PROMPT = `You convert a pasted fitness/ski-training plan (often itself generated by another AI) into structured data for a ski-fitness tracking app called Summit. Call the build_plan tool exactly once with the structured result. Do not respond with plain text.

Guidelines:
- Preserve the plan's real structure: phases (explicit stages like "Phase 1", blocks, or week ranges) each containing routines (named sessions/days/options/workouts), each containing individual activities (exercises).
- If the text has no explicit phases, put everything under a single phase named "Main".
- If a routine has no explicit name, give it a short descriptive one (e.g. "Leg Day").
- For each activity infer: type — "weight" for resistance moves with a load, "reps" for bodyweight rep-based moves, "time" for holds/intervals/ergs measured in seconds, "distance" for cardio measured by distance; sets; reps; durationSec (in seconds); weight plus weightUnit ("kg" unless lb/pounds is used); perLeg (true ONLY if the text explicitly says each leg/side/arm — a bare "each week" or similar does not count); distance plus distanceUnit ("mi" unless km/metric is used).
- ALWAYS fill howTo (one to two plain-English technique cues), equipment (what's needed), muscles (primary muscles worked), and weightGuidance (a short practical note on choosing load or effort) for every activity, even if the source text doesn't include them — use your own fitness knowledge. Keep these concise and in UK English.
- Use sensible defaults when the source is vague (e.g. 3 sets of 10-12 reps for an unspecified strength move, 60 seconds for an unspecified hold).
- If the text states phase-level goals or targets (e.g. "wall sit 90 seconds by end of phase"), put these in that phase's targets array — never as activities inside a routine.
- Fold meta text (weekly frequency notes, general goals, progression philosophy) into the relevant phase's description as a short sentence. Never turn this kind of text into a routine or an activity.
- Never invent phases, routines, or exercises beyond what the source implies.
- Keep exercise names concise Title Case (e.g. "Goblet Squat", not "Goblet squats x3 each side").`;

const BUILD_PLAN_TOOL = {
  name: "build_plan",
  description: "Save the structured training plan extracted from the pasted text.",
  input_schema: {
    type: "object",
    properties: {
      name: { type: "string", description: "Short plan name." },
      description: { type: "string", description: "One sentence overview, optional." },
      phases: {
        type: "array",
        items: {
          type: "object",
          properties: {
            name: { type: "string" },
            description: { type: "string", description: "When this phase runs / its focus, optional." },
            durationWeeks: { type: "integer" },
            routines: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  name: { type: "string" },
                  description: { type: "string" },
                  activities: {
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        name: { type: "string" },
                        type: { type: "string", enum: ["weight", "reps", "time", "distance"] },
                        sets: { type: "integer" },
                        reps: { type: "integer" },
                        durationSec: { type: "integer" },
                        weight: { type: "number" },
                        weightUnit: { type: "string", enum: ["kg", "lb"] },
                        perLeg: { type: "boolean" },
                        distance: { type: "number" },
                        distanceUnit: { type: "string", enum: ["mi", "km"] },
                        howTo: { type: "string" },
                        equipment: { type: "string" },
                        muscles: { type: "string" },
                        weightGuidance: { type: "string" },
                      },
                      required: ["name", "type"],
                    },
                  },
                },
                required: ["name", "activities"],
              },
            },
            targets: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  label: { type: "string" },
                  durationSec: { type: "integer" },
                  reps: { type: "integer" },
                },
                required: ["label"],
              },
            },
          },
          required: ["name", "routines"],
        },
      },
    },
    required: ["name", "phases"],
  },
};

function json(obj, status = 200) {
  return new Response(JSON.stringify(obj), { status, headers: { "content-type": "application/json" } });
}

export async function onRequestPost(context) {
  let body;
  try {
    body = await context.request.json();
  } catch {
    return json({ error: "Invalid request." }, 400);
  }

  const text = (body && body.text ? String(body.text) : "").trim();
  if (!text) return json({ error: "No plan text provided." }, 400);
  if (text.length > 12000) return json({ error: "That's a lot of text — trim it to under 12,000 characters and try again." }, 400);

  const apiKey = context.env.ANTHROPIC_API_KEY;
  if (!apiKey) return json({ error: "The server isn't configured with an Anthropic API key yet." }, 500);

  let resp;
  try {
    resp = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-api-key": apiKey,
        "anthropic-version": ANTHROPIC_VERSION,
      },
      body: JSON.stringify({
        model: MODEL,
        max_tokens: 4096,
        system: SYSTEM_PROMPT,
        messages: [{ role: "user", content: text }],
        tools: [BUILD_PLAN_TOOL],
        tool_choice: { type: "tool", name: "build_plan" },
      }),
    });
  } catch (e) {
    return json({ error: "Couldn't reach the AI service. Check your connection and try again." }, 502);
  }

  if (!resp.ok) {
    const detail = await resp.text().catch(() => "");
    return json({ error: `AI service returned an error (${resp.status}).`, detail: detail.slice(0, 300) }, 502);
  }

  const data = await resp.json();
  const toolUse = (data.content || []).find((b) => b.type === "tool_use" && b.name === "build_plan");
  if (!toolUse) return json({ error: "Didn't get a structured plan back. Try again." }, 502);

  return json({ plan: toolUse.input });
}
